name: inkger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  dart_jsonwebtoken: ^3.2.0
  shelf: ^1.4.2
  dio: ^5.8.0+1
  bcrypt: ^1.1.3
  mysql_client: ^0.0.27
  shelf_cors_headers: ^0.1.5
  flutter_localizations:
    sdk: flutter
  intl: any
  shelf_router: ^1.1.4
  logging: ^1.3.0
  web: ^1.1.1
  file_picker: ^9.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  go_router: ^14.8.1
  mime: ^2.0.0
  flutter_tilt: ^3.2.1
  palette_generator: ^0.3.3+6
  universal_file: ^1.0.0
  archive: ^4.0.5
  xml: ^6.5.0
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  flutter_widget_from_html: ^0.16.0
  flutter_fullscreen: ^1.1.0
  animated_toggle_switch: ^0.8.4
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  fonts:
    - family: fantasy
      fonts:
        - asset: assets/fonts/fantasy.ttf
  assets:
    - assets/images/
    - assets/models/
    - assets/fonts/
  uses-material-design: true
